#! /usr/bin/env bash

ENV='docker'


mkvirtualenv $ENV
setvirtualenvproject $ENV $(pwd)
workon $ENV


echo 'export DOCKER_TLS_VERIFY=1' >> $VIRTUAL_ENV/bin/postactivate
echo 'export DOCKER_HOST=tcp://192.168.59.103:2376' >> $VIRTUAL_ENV/bin/postactivate
echo 'export DOCKER_CERT_PATH=/Users/Jade/.boot2docker/certs/boot2docker-vm' >> $VIRTUAL_ENV/bin/postactivate
